### ISSUE TITLE
FR9. Anonymous Support Groups

### ISSUE THREAD

**Issue by Sabbir999** [WSU-4110/CareConnect#10]
|FR12. Anonymous Support Groups |
|---|
|**Goal**: Establish virtual support groups for users to connect anonymously. |
**Stakeholders:** All Users|
| **Description:** Users can join virtual support groups based on specific mental health issues, allowing them to discuss their challenges anonymously with others facing similar struggles. |
| **Origin:** During our first meeting, we worked together to draft a description that aligned with our project proposal |**Version** 2.0|
|**Date:** 10/25/2023 |
| **Version:** 3.0 |
| **Priority:** 2 |

**Comment by Prangon108** [comment]
Wasn't able to implement in the short time
