### ISSUE TITLE
NF3. Reliability

### ISSUE THREAD

**Issue by Sabbir999** [WSU-4110/CareConnect#11]
|NF3. Reliability|
|---|
|**Goal**:  Ensure the system is operating consistently without any downtime or failures.
**Stakeholders:** All Users|
| **Description:** The ability of the software system to consistently perform its intended functions without any failures. This ensures that the system shall operate as expected over time |
| **Origin:** Group Online Discussion.|
| **Version:** 2.0 |
|**Date:** 10/26/2023
| **Priority:** 2 |

**Comment by Prangon108** [comment]
Due to the limited timeframe and scope, we were unable to thoroughly test the reliability of the system to ensure zero downtime or failures.
