### ISSUE TITLE
NF6. User Feedback Mechanism

### ISSUE THREAD

**Issue by Sabbir999** [WSU-4110/CareConnect#13]
|NF6. User Feedback Mechanism|
|---|
|**Goal**: To gather user input for web app performance, in order to maintain and enhance software systems. 
**Stakeholders:** All Users, System Admin|
| **Description:** Enables users to provide suggestions or complaints about the system's functionality. It will be a way for the user to submit their feedback on the app, which will be sent to the administration. This will help developers progressively improve the system |
| **Origin:** Group project meeting.|
| **Version:** 2.0 |
|**Date:** 11/11/2023
| **Priority:** 2 |

**Comment by Prangon108** [comment]
Successfully implemented
