### ISSUE TITLE
FR6. User Profile Customization

### ISSUE THREAD

**Issue by burahaun** [WSU-4110/CareConnect#15]
|FR6. User Profile Customization|
|---|
|**Goal**: Allow users to have customizable profiles, with things like profile pictures, bios, and other information about themselves.
**Stakeholders:** Registered users|
| **Description:** Users can have customizable profiles similar to existing social medias, like Twitter and Instagram. |
| **Origin:** During our first meeting, we worked together to draft a description that aligned with our project proposal|
| **Version:** 3.0 |
|**Date:** 11/19/2023
| **Priority:** 2 |

**Comment by Prangon108** [comment]
Successfully implemented
