### ISSUE TITLE
FR14. Feedback and Reporting System

### ISSUE THREAD

**Issue by burahaun** [WSU-4110/CareConnect#17]
|FR14. Feedback and Reporting System|
|---|
|**Goal**: Implement a system that allows users to provide feedback, report issues, and submit content-related concerns.
**Stakeholders:** Registered users, platform administrators, content moderators|
| **Description:** Registered users can access the Feedback and Reporting System to submit feedback, report technical issues, or raise concerns about content on the platform. Users can provide details such as the type of issue, a description of the problem or feedback, and attach relevant files or screenshots if necessary. The system will categorize and prioritize feedback and reports for review by administrators and content moderators.|
| **Origin:** The need for a Feedback and Reporting System was identified during user feedback sessions and discussions with platform administrators and content moderators to improve user engagement and address issues promptly.|
| **Version:** 2.0  |  
|**Date:** 10/25/2023  
|  **Priority:** 2 |

**Comment by Prangon108** [comment]
Fully completed
