### ISSUE TITLE
FR1. User Sign In

### ISSUE THREAD

**Issue by Kawsarislam1** [WSU-4110/CareConnect#2]
|**FR1. User Sign In**|
|---|
|**Goal**: Enable users to securely sign in to their accounts. **Stakeholders:** Registered users|
|**Description:** Users can sign in to the website using their registered email and password. The system will provide options for account recovery in case of forgotten credentials.|
|**Origin:** Identified as a critical feature for user accessibility in our second meeting.|
|**Version:** 1.0|
|**Date:** 09/20/2023|
|**Priority:** 2|

**Comment by Prangon108** [comment]
Successfully implemented
