### ISSUE TITLE
FR13. User Photo Customization

### ISSUE THREAD

**Issue by mohanyes** [WSU-4110/CareConnect#20]
|**FR13. User Photo Customization**|
|---|
|**Goal**: Enhance user profile customization by allowing photo uploads. **Stakeholders:** Registered users|
|**Description:** Users will have the ability to upload and change their profile photos, adding a personal touch to their profiles. This feature will include basic photo uploading functionalities, adhering to the project's scope and resources.|
|**Origin:** Conceived during our initial project discussions, focusing on improving user engagement and personalization.|
|**Version:** 3.0|
|**Date:** 11/19/2023|
|**Priority:** 2|

**Comment by Prangon108** [comment]
implemented
