### ISSUE TITLE
NF4. Compatibility

### ISSUE THREAD

**Issue by mohanyes** [WSU-4110/CareConnect#21]
|NF4. Compatibility|
|--|
|**Goal:** Make sure the software system is compatible with various browsers.|
|**Stakeholders:** All Users|
|**Description**: The software system must be compatible with various browsers in order to get maximal user reach. By being compatible people with different types of browsers will still be able to access the web app.|
|**Origin:** Group Online Discussion|
|**Version:** 1.0|
|**Date:** 11/21/2023
|**Priority:** 1|

**Comment by Prangon108** [comment]
Successfully implemented
