### ISSUE TITLE
NF5. Availability

### ISSUE THREAD

**Issue by LucasPrifti** [WSU-4110/CareConnect#22]
|NF5. Availability|
|---|
|**Goal**: Provide an available and accessible web app to users when needed, without any downtime or disruptions.
**Stakeholders:** All Users|
| **Description:**  The web App must be always available and reachable to its customers, ensuring the system remains operational and responsive. High availability is essential for such a system, which intends to provide a service towards the community. |
| **Origin:** Group Project Meeting. |
| **Version:** 1.0 |
|**Date:** 11/21/2023
| **Priority:** 1 |

**Comment by Prangon108** [comment]
Given the scope and timeframe of our school project, we focused on local development, hosting the web app on localhost, which inherently limited our ability to fully test and implement high availability features like real-time accessibility and uninterrupted uptime.
