### ISSUE TITLE
FR2. User Sign Up

### ISSUE THREAD

**Issue by Kawsarislam1** [WSU-4110/CareConnect#3]
|**FR3. User Sign Up**|
|---|
|**Goal**: Facilitate new users in creating an account. **Stakeholders:** New users|
|**Description:** New users can sign up by providing required information such as name, email, and password. The sign-up process includes acceptance of terms and conditions.|
|**Origin:** Suggested in our initial project proposal to expand our user base.|
|**Version:** 1.0|
|**Date:** 09/21/2023|
|**Priority:** 1|

**Comment by Prangon108** [comment]
Successfully implemented
