### ISSUE TITLE
FR5. Email Verification Process

### ISSUE THREAD

**Issue by Kawsarislam1** [WSU-4110/CareConnect#5]
|**FR5. Email Verification Process**|
|---|
|**Goal**: Ensure user account authenticity through email verification. **Stakeholders:** New users|
|**Description:** After signing up, users are required to verify their email address by clicking a link sent to their provided email. This step is mandatory for account activation.|
|**Origin:** Recommended for security purposes during our security audit session.|
|**Version:** 1.0|
|**Date:** 09/23/2023|
|**Priority:** 1|

**Comment by Prangon108** [comment]
Successfully implemented
